language: node_js

node_js:
  - "6"
  - "7"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - node --version
  - npm --version
  - npm run test
